apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
        - name: submission-service
          image: 619924817249.dkr.ecr.ap-southeast-1.amazonaws.com/hiresphere/submission-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
spec:
  selector:
    app: submission-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP